<div id='navigation'>
	<a href=<?= $this->baseUrl('/drh/index/');?>>drh</a>
	<a href=<?= $this->baseUrl('/exploitation/index/');?>>exploitation</a>
	<a href=<?= $this->baseUrl('/commercial/index/');?>>commercial</a>
	<a href=<?= $this->baseUrl('/directionstrategique/index/');?>>direction strategique</a>
	<a href=<?= $this->baseUrl('/planning/index/');?>>planning</a>
	<a href=<?= $this->baseUrl('/maintenance/index/');?>>maintenance</a>
</div>
<?php 
$utilisateurCourant = $this->utilisateurCourant;
$urlAddUti = $this->url(array('controller' => 'administrateur', 'action' => 'ajout'), null, true);
?>
<a href="<?php echo $urlAddUti ?>" >Ajouter</a>
<table class="table_type1">
	<thead>
		<th>Nom</th>
		<th>Prenom</th>
		<th>Login</th>
		<th>Mail</th>
		<th>Poste</th>
	</thead>
<?php
foreach ($utilisateurCourant as $utilisateur){
?>
	<tr class="espace1">
		<td  > <?php echo $utilisateur["UTI_nom"]; ?></td>
		<td><?php echo $utilisateur["UTI_prenom"]; ?></td>
		<td><?php echo $utilisateur["UTI_login"]; ?></td>
		<td><?php echo $utilisateur["UTI_mail"]; ?></td>
		<td> <?php echo utf8_encode($utilisateur["typeUtilisateur"]["TUTI_label"]); ?></td>
	</tr>
<?php
}
?>
</table>