<?php 
	
	// Parcourir le planning
	echo<<<TABLESTART
	<table class="table_type1" >
		<thead>
			<tr>
				<th>Départ</th>
				<th>Aéroport</th>
				<th>Arrivée</th>
				<th>Aéroport</th>
				<th>Avion</th>
				<th>Ligne</th>
				<th>Pilote</th>
				<th>Copilote</th>
			</tr>
		</thead>
		<tbody>
TABLESTART;

		foreach($this->planning as $vol){
			echo<<<TABLEROW
			<tr>
				<td>$vol[depart]</td>
				<td>$vol[nomAeroportDepart]</td>
				<td>$vol[arrivee]</td>
				<td>$vol[nomAeroportArrivee]</td>
				<td></td>
				<td>$vol[ligne]</td>
				<td></td>
				<td></td>
			</tr>
TABLEROW;
		}
	
	echo<<<TABLEEND
		</tbody>
	</table>
TABLEEND;
	
?>