<?php 
	$tabNomJours = array('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche');
	$tabNomMois = array('janvier', 'février', 'mars', 'avril', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre');
	$today = new DateTime();
	$todayFr = $tabNomJours[($today->format('N') - 1)];
	$todayNumber = $today->format('d');
	$todayMois = $tabNomMois[($today->format('n') - 1)];
	$todayWeek = $today->format('W');
	
	// PANNEAU DE CONTROLE D'AFFICHAGE
	echo<<<PANEL
	<div id="panel" >
		<button value="$urlPlanning" class="cinqSemaines actif" >
			<span>Cette semaine + les 4 prochaines</span>
		</button>
		<div class="semaines" >
PANEL;
		$numSemaine = 0;
		foreach($this->panel as $semaine){
			$left = (($numSemaine ) * 148);
			$url = $this->url(array('controller' => 'planning', 'action' => 'index', 'date' => $semaine['value'], 'week' => '1'), null, true);
			echo<<<SEMAINE
			<div class="semaine" style="left:{$left}px;">
				<button value="$url" >semaine $semaine[semaine]<br />{$semaine['jours'][0]['num']} {$semaine['jours'][0]['mois']} {$semaine['jours'][0]['annee']} -> {$semaine['jours'][6]['num']} {$semaine['jours'][0]['mois']}</button>
				<div class="jours">
SEMAINE;
				$numJour = 0;
				foreach($semaine['jours'] as $jour){
					$left = ($numJour * 20) . 'px';
					echo<<<JOUR
					<div class="jour" style="left:$left;">
						<button value="$urlPlanning/$jour[value]" >$jour[label]<br />$jour[num]</button>
					</div>
JOUR;
					$numJour++;
				}
	
			echo<<<SEMAINE
				</div>
			</div>
SEMAINE;
			$numSemaine++;
		}
		echo<<<PANEL
		</div>
	</div>
PANEL;
	
	echo<<<TABLESTART
	<div id="today" >
		<div class="head" >Aujourd'hui</div>
		<div class="body" >
			<p>
				<span>$todayFr</span>
				<br />
				<span>$todayNumber</span>
				<br />
				<span>$todayMois</span>
				<br />
				<span>semaine $todayWeek</span>
			</p>
		</div>
	</div>
	<table class="table_type1" >
		<thead>
			<tr>
				<th>Départ Prévu</th>
				<th>Départ Effectif</th>
				<th>Aéroport</th>
				<th>Arrivée</th>
				<th>Aéroport</th>
				<th>Avion</th>
				<th>Ligne</th>
				<th>Pilote</th>
				<th>Copilote</th>
				<th>Modifier</th>
			</tr>
		</thead>
		<tbody>
TABLESTART;
// Parcourir le planning
		foreach($this->planning as $vol){
		
			if($vol['id'] > 0){
				$urlPlanifier = $this->url(array('controller' => 'planning', 'action' => 'planifier', 'id' => $vol['id']), null, true);
				$label = 'Modifier';
			}
			else{
				$urlPlanifier = $this->url(array('controller' => 'planning', 'action' => 'creer', 'ligne' => $vol['ligne'], 'aeroportDepart' => $vol['depart']['idAeroport'], 'aeroportArrivee' => $vol['arrivee']['idAeroport'], 'date' => $vol['depart']['dateurl']), null, true);
				$label = 'Planifier';
			}
			echo<<<TABLEROW
			<tr class="{$vol['class']}" >
				<td>{$vol['depart']['prevu']}</td>
				<td>{$vol['depart']['date']}</td>
				<td>{$vol['depart']['nomAeroport']}</td>
				<td>{$vol['arrivee']['date']}</td>
				<td>{$vol['arrivee']['nomAeroport']}</td>
				<td>{$vol['avion']['immatriculation']}</td>
				<td>{$vol['ligne']}</td>
				<td>{$vol['pilote']['nom']}</td>
				<td>{$vol['copilote']['nom']}</td>
				<td><a href="$urlPlanifier" >$label</a></td>
			</tr>
TABLEROW;
		}
	
	echo<<<TABLEEND
		</tbody>
	</table>
TABLEEND;
	
?>
<script>
$(document).ready(function() {
	$('#panel').on('click', 'button', function(event){
		$.ajax({
			url: $(this).attr('value')
		}).done(function (data){
			
			console.log('OK');
			
			
		});
	});
});
</script>