<?php 
// Parcourir le planning
foreach($this->planning as $vol){
	switch($vol['class']){
		case 'passe' :
			$urlPlanifier = $this->url(array('controller' => 'planning', 'action' => 'afficher', 'id' => $vol['id']), null, true);
			$label = 'Afficher';
			break;
		case 'planifie' : 
			$urlPlanifier = $this->url(array('controller' => 'planning', 'action' => 'planifier', 'id' => $vol['id']), null, true);
			$label = 'Modifier';
			break;
		case 'non-planifie' :
			$urlPlanifier = $this->url(array('controller' => 'planning', 'action' => 'creer', 'ligne' => $vol['ligne'], 'aeroportDepart' => $vol['depart']['idAeroport'], 'aeroportArrivee' => $vol['arrivee']['idAeroport'], 'date' => $vol['depart']['dateurl']), null, true);
			$label = 'Planifier';
			break;
	}

	echo<<<TABLEROW
	<tr class="{$vol['class']}" >
		<td>{$vol['depart']['prevu']}</td>
		<td>{$vol['depart']['date']}</td>
		<td>{$vol['depart']['nomAeroport']}</td>
		<td>{$vol['arrivee']['date']}</td>
		<td>{$vol['arrivee']['nomAeroport']}</td>
		<td>{$vol['avion']['immatriculation']}</td>
		<td>{$vol['ligne']}</td>
		<td>{$vol['pilote']['nom']}</td>
		<td>{$vol['copilote']['nom']}</td>
		<td><a href="$urlPlanifier" >$label</a></td>
	</tr>
TABLEROW;
}
	
?>