<?php
$urlRetour = $this->url(array('controller' => 'planning', 'action' => 'index'), null, true);
echo<<<VOL
<h2>Modifier un vol planifié</h2>
<a href="$urlRetour" >Retour au planning</a>
<br />
<span>Ligne : $this->ligne</span><br />
<span>Aéroport de Départ : $this->aeroportDepart</span><br />
<span>Aéroport d'Arrivée : $this->aeroportArrivee</span><br />
<span>Date de départ Prévue : $this->datePrevue</span>
$this->formPlanifier
VOL;
