<section id="index" >
	<div id="avion">
		<img src="<?php echo $this->baseUrl(); ?>/img/avion.png" alt="silhouette d'avion" />
	</div>
	<?php 
	if(isset($this->error)){
		echo<<<ERROR
		<p>
			<span>$this->error</span>
		</p>
ERROR;
	}
	
	if(isset($this->dejaConnecte)) { 
		
		$urlDeconnexion = $this->url(array('controller' => 'index', 'action' => 'deconnexion'), null, true);
		$urlAcces = $this->url(array('controller' => $this->dejaConnecte, 'action' => 'index'), null, true);
		
		echo<<<DEJACO
		<p>
			<span>Vous êtes déjà connecté en tant que : $this->dejaConnecte</span>
			<br />
			<a href="$urlAcces" >Accéder à votre page</a>
			<br />
			<a href="$urlDeconnexion" >Se Déconnecter</a>
		</p>
DEJACO;
	} 
	else{
	?>
	<fieldset id="fieldsetConnexion" >
		<?php echo $this->formConnexion ?>
	</fieldset>
	<table class="table_type1" >
		<caption>Authentification</caption>
		<thead>
			<tr>
				<th>Rôle</th>
				<th>Login</th>
				<th>Mot de Passe</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Administrateur</td>
				<td>kevin</td>
				<td>kevin</td>
			</tr>
			<tr>
				<td>Direction des Ressources Humaines</td>
				<td>abdallah</td>
				<td>abdallah</td>
			</tr>
			<tr>
				<td>Direction Stratégique</td>
				<td>antoine</td>
				<td>antoine</td>
			</tr>
			<tr>
				<td>Service Maintenance</td>
				<td>macey</td>
				<td>macey</td>
			</tr>
			<tr>
				<td rowspan="3" >Pilote</td>
				<td>looping</td>
				<td>looping</td>
			</tr>
			<tr>
				<td>gun</td>
				<td>gun</td>
			</tr>
			<tr>
				<td>barrelroll</td>
				<td>barrelroll</td>
			</tr>
			<tr>
				<td>Service Planning</td>
				<td>conan</td>
				<td>conan</td>
			</tr>
		</tbody>
	</table>
	<?php
	}
	?>
</section>