<section id="index" >
	<div id="avion">
		<img src="<?php echo $this->baseUrl(); ?>/img/avion.png" alt="silhouette d'avion" />
	</div>
	<fieldset id="fieldsetConnexion" >
		<?php echo $this->formConnexion ?>
	</fieldset>
	<table class="table_type1" >
		<caption>Authentification</caption>
		<thead>
			<tr>
				<th>Rôle</th>
				<th>Login</th>
				<th>Mot de Passe</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Administrateur</td>
				<td>kevin</td>
				<td>kevin</td>
			</tr>
			<tr>
				<td>Direction des Ressources Humaines</td>
				<td>abdallah</td>
				<td>abdallah</td>
			</tr>
			<tr>
				<td>Direction Stratégique</td>
				<td>antoine</td>
				<td>antoine</td>
			</tr>
			<tr>
				<td>Service Maintenance</td>
				<td>macey</td>
				<td>macey</td>
			</tr>
			<tr>
				<td rowspan="3" >Pilote</td>
				<td>looping</td>
				<td>looping</td>
			</tr>
			<tr>
				<td>gun</td>
				<td>gun</td>
			</tr>
			<tr>
				<td>barrelroll</td>
				<td>barrelroll</td>
			</tr>
			<tr>
				<td>Service Planning</td>
				<td>conan</td>
				<td>conan</td>
			</tr>
		</tbody>
	</table>
</section>