<script type="text/javascript">
	jQuery(function($){
		urlTerminer = "<?php echo $this->baseUrl('maintenance/terminer')?>";
		urlCommencer = "<?php echo $this->baseUrl('maintenance/commencer')?>";
		$("#dateDebutMaintenance").datepicker({ autoSize: true, dateFormat: "yy-mm-dd" });
		$("#dialog").dialog({autoOpen: false , width: 400});
	});
</script>
<?php 
$avionsDisponibilite = $this->avionsDisponibilite;
?>
<table class="table_type1">
	<thead>
		<th>Immatriculation</th>
		<th>Types d'avion</th>
		<th>Petitte maintenance</th>
		<th>Grande maintenance</th>
		<th>Date de début</th>
		<th>Disponibilité</th>
	</thead>
<?php
foreach ($avionsDisponibilite as $avion){
?>
	<tr>
		<td>
<?php
			echo $avion["AVI_immatriculation"];
?>
		</td>
		<td>
<?php
			echo $avion["typesAvion"]["TAVI_nom"];
?>
		</td>
		<td class="<?php echo $avion["maintenanceType"];?>">
<?php
			echo $avion["AVI_heureDeVolsDepuisPetiteMaintenance"]."/".$avion["typesAvion"]["TAVI_periodicitePetiteMaintenance"];
?>
		</td>
		<td class="<?php echo $avion["maintenanceType"];?>">
<?php
			echo $avion["AVI_heureDeVolsDepuisGrandeMaintenance"]."/".$avion["typesAvion"]["TAVI_periodiciteGrandeMaintenance"];
?>
		</td>
		<td class="<?php echo $avion["maintenanceType"];?>">
<?php
			echo $avion["maintenance"]["dateDebut"];
?>
		</td>
		<td>
<?php
			if ($avion["action"] == "disponible") {
				echo "Disponible";
			}else{
?>
				<button id="<?php echo $avion["AVI_id"];?>" class="<?php echo $avion["action"]." ".$avion["maintenanceType"];?>" ><?php echo $avion["actionLabel"];?></button>
<?php 
			}
?>
		</td>
	</tr>
<?php
}
?>
</table>
 
<div id="dialog" title="Creation maintenance">
<?php 
		echo $this->ajouterMaintenanceForm;
?>
</div>