<?php 
	$this->headTitle()->SetSeparator(' - ');
	$this->headTitle('INSSET Airlines');
	echo $this->doctype('HTML5');
?>
<!DOCTYPE html>
<html lang="fr" >
	<head>
		<meta charset="utf-8" /> 

		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/reset.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/stylegeneral.css" />
		<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/js/css/smoothness/jquery-ui-1.10.0.custom.min.css" />
		<!--[if IE]>
			<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/css/ie.css" />
		<![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
	<script src="<?php echo $this->baseUrl();?>/js/js/jquery-ui-1.10.0.custom.min.js"></script>
		
		<!-- Script qui met à disposition la baseUrl pour les autres scripts JS -->
		<!-- ça sert par exemple pour l'ajax -->
		<script>var baseUrl = "<?php echo $this->baseUrl() ?>";</script>
		
		<script src="<?php echo $this->baseUrl();?>/js/fonction.js"></script>
		<?php echo $this->headTitle() ?>
		
	</head>
	<body>
		<div id="bodyPage">
		
			
				<!-- HEADER -->	
				<header>
					<img  src="<?php echo $this->baseUrl(); ?>/img/logo.jpg" alt="Logo Insset Airlines" />

				<?php
					if(isset($this->layout()->login)){
						
						$urlDeconnexion = $this->url(array('controller' => 'index', 'action' => 'deconnexion'), null, true);
					
						echo<<<INFOSCO
						<div id='identification' class="right">
							<span>Bienvenue, {$this->layout()->login} - {$this->layout()->roleLabel}</span><br/><br/>
							<a href="$urlDeconnexion" >Déconnexion</a>
						</div>
INFOSCO;
					if($this->layout()->role == 'administrateur'){
						?>
						<div id='navigation'>
	<a class="menu" href=<?= $this->baseUrl('/drh/index/');?>>drh</a>
	<a class="menu" href=<?= $this->baseUrl('/exploitation/index/');?>>exploitation</a>
	<a class="menu" href=<?= $this->baseUrl('/commercial/index/');?>>commercial</a>
	<a class="menu" href=<?= $this->baseUrl('/directionstrategique/index/');?>>direction strategique</a>
	<a  class="menu" href=<?= $this->baseUrl('/planning/index/');?>>planning</a>
	<a class="menu" href=<?= $this->baseUrl('/maintenance/index/');?>>maintenance</a>
</div>
						<?php
					}
					
					}
				?>
				</header>
					

					
				<!-- CONTAINER -->			
				<?php echo $this->layout()->content; ?>
					
				<!-- FOOTER -->
				<footer>
				</footer>
				
		</div>
	</body>
</html>


