<?php 
	echo 'ds/modifierligne';
	echo '<br />';
	$auth = Zend_Auth::getInstance();
	$identity = $auth->getIdentity();
?>
<div id='identification'>
<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'deconnexion')) ?>">Deconnexion</a>
<?php echo 'Bienvenue ' . $identity->UTI_login . ' ';?>
</div>
<br />	
<br />
<div class='message'>
<?php echo $this->message;?>
</div>
<h1>Ajouter une ligne</h1>
<div id="menuDs">
	<ol>
		<li><a href="<?php echo $this->url(array('controller' => 'directionstrategique', 'action' => 'index')) ?>">Annuler</a></li>
	</ol>
</div>
<?php
	 echo $this->formAjouterLigne;

?>
