<?php 
	echo 'ds/modifierligne';
	echo '<br />';
	$auth = Zend_Auth::getInstance();
	$identity = $auth->getIdentity();
?>
<div id='identification'>
<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'deconnexion')) ?>">Deconnexion</a>
<?php echo 'Bienvenue ' . $identity->UTI_login . ' ';?>
</div>
<br />	
<br />
<h1>Ajouter une ligne</h1>
<div id="menuDs">
	<ol>
		<li><a href="<?php echo $this->url(array('controller' => 'directionstrategique', 'action' => 'index')) ?>">Annuler</a></li>
	</ol>
</div>
<?php
	echo $this->formAjouterLigne;
	
	echo "<select name='a1'";
	if(isset($_POST["idPays"])){
		echo $_POST["idPays"];
		$db = Zend_Registry::get('db');
		$aeroport = new Application_Model_DbTable_Aeroport();
		$aeroports = $aeroport->aeroportPays($_POST["idPays"]);
		foreach($aeroports as $a) {
			echo "<option value='".$row["AER_id"]."'>".$row["AER_nom"]."</option>";
		}
	}
	else echo 'erreur';
	echo "</select>";
