<?php 
	echo 'ds/index';
	echo '<br />';
	$auth = Zend_Auth::getInstance();
	$identity = $auth->getIdentity();
	echo 'Bienvenue ' . $identity->UTI_login . ' ';
?>
<a href="/index/deconnexion">Deconnexion</a>
<br />	
<br />
<div id="menuDs">
	<ol>
		<li><a href="/directionstrategique/ajouterligne">Ajouter des lignes</a></li>
		<li><a href="/directionstrategique/modifierligne">Modifier des lignes</a></li>
	</ol>
</div>
____________________________________________ 
<br />
<table>
	<tr>
		<th>Id</th>
		<th>Aéroport de départ</th>
		<th>Aéroport d'arrivé</th>
	</tr>
<?php foreach($this->lignes as $ligne) : ?>
	<tr>
		<td><?php echo $ligne['LIG_id'];?>
		<td><?php //echo $ligne['Depart'];?></td>
		<td><?php //echo $ligne['Arrive'];?></td>
	</tr>
<?php endforeach;?>	
</table>



	
	
	
	