<?php 
	echo 'ds/index';
	echo '<br />';
	$auth = Zend_Auth::getInstance();
	$identity = $auth->getIdentity();
?>
<div id='identification'>
<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'deconnexion')) ?>">Deconnexion</a>
<?php echo 'Bienvenue ' . $identity->UTI_login . ' ';?>
</div>
<br />	
<br />
<h1>Liste des Lignes</h1>
<div id="menuDs">
	<ol>
		<li><a href="<?php echo $this->url(array('controller' => 'directionstrategique', 'action' => 'ajouterligne')) ?>">Ajouter des lignes</a></li>
	</ol>
</div>
____________________________________________ 
<br />
<table>
	<tr>
		<th>Id ligne</th>
		<th>Ville de départ</th>
		<th>Aéroport de départ</th>
		<th>Ville d'arrivée
		<th>Aéroport d'arrivé</th>
		<th></th>
		<th></th>
	</tr>
<?php 
foreach($this->lignes as $ligne) : ?>
	<tr>
		<td><?php echo $ligne['id'];?>
		<td><?php echo $ligne['nomVilleDepart'];?></td>
		<td><?php echo $ligne['nomAeroportDepart'];?></td>
		<td><?php echo $ligne['nomVilleArrivee'];?></td>
		<td><?php echo $ligne['nomAeroportArrivee'];?></td>
		<td><a href="<?php echo $this->url(array('controller' => 'directionstrategique', 'action' => 'modifierligne', 'id' => $ligne['id'])) ?>">Modifier la ligne</a></td>
		<td><a href="<?php echo $this->url(array('controller' => 'directionstrategique', 'action' => 'supprimerligne', 'id' => $ligne['id'])) ?>">Supprimer la ligne</a></td>
	</tr>
<?php endforeach;?>	
</table>



	
	
	
	