<?php 
	$auth = Zend_Auth::getInstance();
	$identity = $auth->getIdentity();
?>
  <script type="text/javascript">
 $(function() {
        $("#heureDepart").datetimepicker({timeOnly: true, timeFormat: "hh:mm"});
        $("#heureArrivee").datetimepicker({timeOnly: true, timeFormat: "hh:mm"});
    });

  </script>
<br />	
<br />
<h1>Modifier une Ligne</h1>
<div id="menuDs">
	<ol>
		<li><a href="<?php echo $this->url(array('controller' => 'directionstrategique', 'action' => 'index')) ?>">Annuler</a></li>
	</ol>
</div>
<?php echo $this->form ?>




	
	
	
	